# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "algorithms", :force => true do |t|
    t.column "name",       :string
    t.column "author",     :string
    t.column "code",       :text
    t.column "password",   :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "boards", :force => true do |t|
    t.column "algorithm_x_id", :integer
    t.column "algorithm_o_id", :integer
    t.column "history",        :text
    t.column "updated_at",     :datetime
    t.column "created_at",     :datetime
    t.column "forfeit",        :string
  end

  create_table "moves", :force => true do |t|
    t.column "board_id",   :integer
    t.column "x_pos",      :integer
    t.column "y_pos",      :integer
    t.column "is_x",       :boolean
    t.column "created_at", :datetime
  end

end
